### ISSUE TITLE
Language switcher en/ja

### ISSUE THREAD

**Issue by wmeddie** [XpressAI/technologic#17]
![Image](https://github.com/XpressAI/technologic/assets/122480/2170e19c-1d6b-4f03-8df1-c24012132bc5)

Should have a Language page in the settings that allows the user to switch to a different language.

**Comment by kinxiel** [comment]
What is the end form for deployment? Is the site mostly going to be deployed as static? 
Currently checking several options for i18n, just wondering which one would be a good fit.

**Comment by treo** [comment]
Yeah, technologic runs entirely in the browser and is built as an SPA without any own backend.

**Comment by kinxiel** [comment]
After checking some of the most common i18n solutions in the Svelte ecosystem, I came up with the simple summary below. I will add more details in the Discord.

|  | Description | Ease of Use | Actively Maintained |
| ---- | ---- | ---- | ---- |
| svelte-i18n | - for base Svelte, can be adapter for SvelteKit | Simple | No |
| sveltekit-i18n | - for Sveltekit | Simple | Yes |
| typesafe-i18n | - Framework Agnostic<br>- Most complete solution<br>- Most mature | Need some getting used to the ecosystem, but will probably pay off later. | Yes |

**Comment by treo** [comment]
@wmeddie 
There are still a few strings that aren't translated. Do we want to keep this issue open until this is taken care of?

**Comment by wmeddie** [comment]
Yeah. We can get to those eventually and then reference this issue in the PR.
